image: '${DOCKER_REG}/public/ubuntu:18.04'

variables:
  # 定义npm源
  NPM_REG: 'https://registry.npmmirror.com/'
  # 镜像地址
  DOCKER_IMAGE: 'reg.real-ai.cn/frontend-demo/fe'
  # 镜像tag
  DOCKER_TAG: 'v1.0'
  # 目标服务器
  DST_HOSTS: '10.1.10.82'

stages:
  - 'install(依赖)'
  - 'build(构建)'
  - 'buildImage(打包镜像)'
  - 'deploy(部署)'
include:
  - local: '.gitlab/ci/job-install.yml'
  - local: '.gitlab/ci/job-build-dist.yml'
  - local: '.gitlab/ci/job-build-image.yml'
  - local: '.gitlab/ci/job-deploy.yml'